# These are supported funding model platforms

github: # [@DawallAZllon91]
patreon: # @DawallAZllon91

## Hola, soy DawallAZllon91 👋

¡Gracias por visitar mi perfil! Soy un apasionado de la programación y estoy comprometido con aprender y compartir conocimientos. Si encuentras útiles mis proyectos o contenido, considera apoyarme:

- 🌟 **Sponsor**: Puedes convertirte en mi patrocinador en GitHub. Tu apoyo me ayudará a seguir creando y compartiendo contenido.
- 💰 **Donaciones**: También acepto donaciones a través de PayPal. Mi correo para donaciones es azamaralonsodavidoswaldo@gmail.com.

¡Cualquier apoyo es muy apreciado! Juntos podemos seguir construyendo una comunidad de aprendizaje y crecimiento. ¡Gracias! 🙌
